name: Scan and Generate Build YML

on:
  workflow_dispatch:

jobs:
  generate-build-yml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run scanner.js to generate build-android.yml
        run: node .github/workflows/scanner.js

      - name: Show generated build-android.yml in logs
        run: cat .github/workflows/build-android.yml

      - name: Upload generated build-android.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-android-yml
          path: .github/workflows/build-android.yml
