name: Generate Android Build YML

on:
  workflow_dispatch: # možeš pokrenuti ručno iz GitHub UI

jobs:
  generate-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run scanner
        run: node .github/workflows/scanner.js

      - name: Upload generated YML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-android-yml
          path: .github/workflows/build-android.yml
